### ISSUE TITLE
What about div that breaks between pages?

### ISSUE THREAD

**Issue by Vishal1419** [captray-zz/react-print#4]
![react app - google chrome_3](https://user-images.githubusercontent.com/19953475/37484608-063297aa-28af-11e8-9c59-89d18cf66137.jpg)

How to create print area, so that if div does not fit the remaining space, then it goes to the next page?
Also, how to remove the headers and footers on the page?

**Comment by shahzeb1** [comment]
So I looked into this and found this [stack overflow answer](https://stackoverflow.com/questions/8228088/remove-header-and-footer-from-window-print).

Try adding the following style to a .css file:

```css
@media print {
  @page { margin: 0; }
  body { margin: 1.6cm; }
}
```
